name: sample
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.3
  flutter_vector_icons: ^2.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  table_calendar: ^3.1.2
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  intl: ^0.19.0
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  path: ^1.9.0
  supabase_flutter: ^2.8.1
  file_picker: ^8.1.4
  dotted_border: ^2.1.0
  json_annotation: ^4.9.0
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # hive_generator: ^2.0.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/IMG_8718.jpg
    - assets/images/IMG_0823.jpg
    - assets/images/IMG_8731.jpg


