// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnFeA0jTq16ToEqQQebcC6tvyDJSSfVdQ',
    appId: '1:949587554725:web:0fb1413b6729a8c433384c',
    messagingSenderId: '949587554725',
    projectId: 'sotutenn-app-b208c',
    authDomain: 'sotutenn-app-b208c.firebaseapp.com',
    storageBucket: 'sotutenn-app-b208c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoEvlK09J8xXOQ5XROLlDTRrEd4Nun7zA',
    appId: '1:949587554725:android:3800486598089ffc33384c',
    messagingSenderId: '949587554725',
    projectId: 'sotutenn-app-b208c',
    storageBucket: 'sotutenn-app-b208c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ZPdhAVe_ZtEjJjv9HFJyx6xTX8BH9Yk',
    appId: '1:949587554725:ios:e1d59a7f9708a33b33384c',
    messagingSenderId: '949587554725',
    projectId: 'sotutenn-app-b208c',
    storageBucket: 'sotutenn-app-b208c.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ZPdhAVe_ZtEjJjv9HFJyx6xTX8BH9Yk',
    appId: '1:949587554725:ios:e1d59a7f9708a33b33384c',
    messagingSenderId: '949587554725',
    projectId: 'sotutenn-app-b208c',
    storageBucket: 'sotutenn-app-b208c.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnFeA0jTq16ToEqQQebcC6tvyDJSSfVdQ',
    appId: '1:949587554725:web:c87f91ca1ca6758533384c',
    messagingSenderId: '949587554725',
    projectId: 'sotutenn-app-b208c',
    authDomain: 'sotutenn-app-b208c.firebaseapp.com',
    storageBucket: 'sotutenn-app-b208c.firebasestorage.app',
  );

}